services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    env_file: ./.env
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:${DOCKER_PORT} altered_datum_api.wsgi"
    container_name: ${ENV_PROJECT_NAME}
    # volumes:
    #   - .:/app  # Disabled for production
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    restart: unless-stopped